### PR TITLE
LPS-125528 buildRest

### PR DESCRIPTION
**Pull request by marcosapmf**
Related Issue: https://issues.liferay.com/browse/LPS-125528

### CODE REVIEW

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by marcosapmf** [comment]
Hey @nhpatt could you please take a look at this pull?
We are deprecating the Forms Headless Operations first. After that, we intend to do it for the whole schema as I said to you on slack :)

Thanks in advance

**Comment by natocesarrego** [comment]
@marcosapmf, @nhpatt is on vacation, can you please forward this pull to the user `liferay-headless`?

Thanks.

**Comment by marcosapmf** [comment]
forwarded https://github.com/liferay-headless/liferay-portal/pull/535

**Comment by nhpatt** [comment]
Already in master, thanks for sending it directly, I was on paternity leave :(

**Pull request closed without merging**
