### PR TITLE
LPS-112101 missing tests 2

### PR DESCRIPTION
**Pull request by nhpatt**

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:forward

**Comment by jpince** [comment]
@nhpatt the failure was in the first run, please check the results before retesting. Talk to @manoelcyreno about how to view the results if you can't see all of them in the GitHub comment.
```
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/account/account-rest-test/src/testIntegration/java/com/liferay/account/rest/resource/v1_0/test/BaseAccountResourceTestCase.java:51: error: package com.liferay.portal.search.test.util does not exist
     [exec] import com.liferay.portal.search.test.util.SearchTestRule;
     [exec]                                           ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/account/account-rest-test/src/testIntegration/java/com/liferay/account/rest/resource/v1_0/test/BaseAccountResourceTestCase.java:795: error: cannot find symbol
     [exec] 	public SearchTestRule searchTestRule = new SearchTestRule();
     [exec] 	       ^
     [exec]   symbol:   class SearchTestRule
     [exec]   location: class BaseAccountResourceTestCase
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/account/account-rest-test/src/testIntegration/java/com/liferay/account/rest/resource/v1_0/test/BaseAccountUserResourceTestCase.java:50: error: package com.liferay.portal.search.test.util does not exist
     [exec] import com.liferay.portal.search.test.util.SearchTestRule;
     [exec]                                           ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/account/account-rest-test/src/testIntegration/java/com/liferay/account/rest/resource/v1_0/test/BaseAccountUserResourceTestCase.java:719: error: cannot find symbol
     [exec] 	public SearchTestRule searchTestRule = new SearchTestRule();
     [exec] 	       ^
     [exec]   symbol:   class SearchTestRule
     [exec]   location: class BaseAccountUserResourceTestCase
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/account/account-rest-test/src/testIntegration/java/com/liferay/account/rest/resource/v1_0/test/BaseAccountResourceTestCase.java:795: error: cannot find symbol
     [exec] 	public SearchTestRule searchTestRule = new SearchTestRule();
     [exec] 	                                           ^
     [exec]   symbol:   class SearchTestRule
     [exec]   location: class BaseAccountResourceTestCase
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/account/account-rest-test/src/testIntegration/java/com/liferay/account/rest/resource/v1_0/test/BaseAccountUserResourceTestCase.java:719: error: cannot find symbol
     [exec] 	public SearchTestRule searchTestRule = new SearchTestRule();
     [exec] 	                                           ^
```

**Comment by nhpatt** [comment]
Oh, sorry, thanks!

**Pull request closed without merging**
