### PR TITLE
LPS-106492 SF

### PR DESCRIPTION
**Pull request by ruben-pulido**

### CODE REVIEW

**Comment by nhpatt** [comment]
I propose this:

```
components:
    schemas:
        ColumnDefinition:
            properties:
                size:
                    maximum: 12
                    minimum: 1
                    type: integer
            type: object
        FragmentContentFieldBackgroundImage:
            properties:
                backgroundImage:
                    $ref: "#/components/schemas/FragmentImage"
            type: object
        FragmentContentFieldHTML:
            properties:
                html:
                    oneOf:
                        - $ref: "#/components/schemas/InlineValue"
                        - $ref: "#/components/schemas/MappedValue"
            type: object
        FragmentContentFieldImage:
            properties:
                image:
                    $ref: "#/components/schemas/FragmentImage"
            type: object
        FragmentContentFieldText:
            properties:
                text:
                    oneOf:
                        - $ref: "#/components/schemas/InlineValue"
                        - $ref: "#/components/schemas/MappedValue"
            type: object
        FragmentDefinition:
            properties:
                fragmentContentFields:
                    items:
                        $ref: "#/components/schemas/FragmentContentField"
                    type: array
                fragmentCollectionName:
                    type: string
                fragmentConfig:
                    additionalProperties:
                        type: object
                    type: object
                fragmentName:
                    type: string
            type: object
        FragmentContentField:
            properties:
                id:
                    type: string
                link:
                    $ref: "#/components/schemas/FragmentLink"
                value:
                    oneOf:
                        - $ref: "#/components/schemas/FragmentContentFieldBackgroundImage"
                        - $ref: "#/components/schemas/FragmentContentFieldHTML"
                        - $ref: "#/components/schemas/FragmentContentFieldImage"
                        - $ref: "#/components/schemas/FragmentContentFieldText"
            type: object
        FragmentImage:
            properties:
                title:
                    oneOf:
                        - $ref: "#/components/schemas/InlineValue"
                        - $ref: "#/components/schemas/MappedValue"
                url:
                    oneOf:
                        - $ref: "#/components/schemas/InlineValue"
                        - $ref: "#/components/schemas/MappedValue"
            type: object
        FragmentLink:
            properties:
                target:
                    enum: [Blank, Self]
                    type: string
                value:
                    oneOf:
                        - $ref: "#/components/schemas/InlineLink"
                        - $ref: "#/components/schemas/MappedValue"
        InlineLink:
            properties:
                href:
                    type: string
            type: object
        InlineValue:
            properties:
                value:
                    type: string
                value_i18n:
                    additionalProperties:
                        type: object
                    type: object
            type: object
        MappedValue:
            properties:
                classNameId:
                    format: int64
                    readOnly: true
                    type: integer
                classPK:
                    format: int64
                    readOnly: true
                    type: integer
                fieldId:
                    readOnly: true
                    type: string
        PageDefinition:
            description:
                ""
            properties:
                collectionName:
                    readOnly: true
                    type: string
                dateCreated:
                    format: date-time
                    readOnly: true
                    type: string
                dateModified:
                    format: date-time
                    readOnly: true
                    type: string
                friendlyURLPath:
                    type: string
                id:
                    format: int64
                    readOnly: true
                    type: integer
                keywords:
                    items:
                        type: string
                    type: array
                name:
                    type: string
                pageElements:
                    items:
                        $ref: "#/components/schemas/PageElement"
                    type: array
                settings:
                    properties:
                        lookAndFeel:
                            properties:
                                colorSchemeName:
                                    type: string
                                css:
                                    type: string
                                javascript:
                                    type: string
                                themeName:
                                    type: string
                                themeSetttings:
                                    type: object
                            type: object
                        masterPage:
                            properties:
                                name:
                                    type: string
                            type: object
                    type: object
                taxonomyCategories:
                    items:
                        properties:
                            taxonomyCategoryId:
                                format: int64
                                type: integer
                            taxonomyCategoryName:
                                type: string
                        type: object
                    readOnly: true
                    type: array
                taxonomyCategoryIds:
                    items:
                        format: int64
                        type: integer
                    type: array
                    writeOnly: true
                uuid:
                    description:
                        A valid external identifier to reference this structured content.
                    readOnly: true
                    type: string
            type: object
        PageElement:
            properties:
                definition:
                    oneOf:
                        - $ref: "#/components/schemas/ColumnDefinition"
                        - $ref: "#/components/schemas/FragmentDefinition"
                        - $ref: "#/components/schemas/RowDefinition"
                        - $ref: "#/components/schemas/SectionDefinition"
                pageElements:
                    items:
                        $ref: "#/components/schemas/PageElement"
                    type: array
                type:
                    enum: [Column, Fragment, Row, Section]
                    type: string
        RowDefinition:
            properties:
                gutters:
                    type: boolean
                numberOfColumns:
                    format: int32
                    type: integer
            type: object
        SectionDefinition:
            properties:
                backgroundColorCssClass:
                    type: string
                backgroundImage:
                    $ref: "#/components/schemas/FragmentImage"
                containerType:
                    enum: [Fixed, Fluid]
                    type: string
                paddingBottom:
                    format: int32
                    type: integer
                paddingHorizontal:
                    format: int32
                    type: integer
                paddingTop:
                    format: int32
                    type: integer
            type: object
info:
    description:
        ""
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "Headless Delivery"
    version: v1.0
openapi: 3.0.1
paths:
    "/sites/{siteId}/page-templates/{pageTemplateId}":
        get:
            description:
                Retrieve the page template.
            parameters:
                - in: path
                  name: siteId
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: path
                  name: pageTemplateId
                  required: true
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/PageDefinition"
                        application/xml:
                            schema:
                                $ref: "#/components/schemas/PageDefinition"
                    description:
                        ""
            tags: ["PageTemplate"]
```

**Comment by nhpatt** [comment]
if this is Ok, we avoid invalid uses of oneOf/allOf and we can generate the profile as it is.

**Comment by ruben-pulido** [comment]
Was removing creator from PageDefinition intentional?

**Comment by nhpatt** [comment]
No, sólo quitar problemas.

**Comment by nhpatt** [comment]
Closing while you iterate :)

**Pull request closed without merging**
