### PR TITLE
LPS-129736 headless-user-admin API allow changing customFields value

### PR DESCRIPTION
**Pull request by jgarcialr**

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
Oh, I thought you wrote the _toMap code and seeing so much code I wanted to check it in depth, but it's the same as delivery so I delayed it for nothing, sorry :'(

**Comment by nhpatt** [comment]
ci:forward

**Pull request closed without merging**
