### PR TITLE
LPS-107972 search test rule 2

### PR DESCRIPTION
**Pull request by nhpatt**

### CODE REVIEW

**Comment by nhpatt** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:forward

**Comment by jpince** [comment]
@nhpatt please read results before retesting
```
     [exec] > Task :apps:account:account-rest-test:compileTestIntegrationJava
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/account/account-rest-test/src/testIntegration/java/com/liferay/account/rest/resource/v1_0/test/BaseAccountUserResourceTestCase.java:50: error: package com.liferay.portal.search.test.util does not exist
     [exec] import com.liferay.portal.search.test.util.SearchTestRule;
     [exec]                                           ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/account/account-rest-test/src/testIntegration/java/com/liferay/account/rest/resource/v1_0/test/BaseAccountUserResourceTestCase.java:719: error: cannot find symbol
     [exec] 	public SearchTestRule searchTestRule = new SearchTestRule();
     [exec] 	       ^
     [exec]   symbol:   class SearchTestRule
     [exec]   location: class BaseAccountUserResourceTestCase
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/account/account-rest-test/src/testIntegration/java/com/liferay/account/rest/resource/v1_0/test/BaseAccountResourceTestCase.java:795: error: cannot find symbol
     [exec] 	public SearchTestRule searchTestRule = new SearchTestRule();
     [exec] 	                                           ^
     [exec]   symbol:   class SearchTestRule
     [exec]   location: class BaseAccountResourceTestCase
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/account/account-rest-test/src/testIntegration/java/com/liferay/account/rest/resource/v1_0/test/BaseAccountUserResourceTestCase.java:719: error: cannot find symbol
     [exec] 	public SearchTestRule searchTestRule = new SearchTestRule();
     [exec] 	                                           ^
```

**Comment by nhpatt** [comment]
ci:forward

**Pull request closed without merging**
