### PR TITLE
LPS-107616 Applies new Editor to Questions App

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by nhpatt** [comment]
Thank you so much! :D

**Comment by nhpatt** [comment]
Sent here: https://github.com/brianchandotcom/liferay-portal/pull/83781#issuecomment-578417122 :)

**Pull request merged**
