### PR TITLE
LPS-90799 Change version and share the jars instead of copying them

### PR DESCRIPTION
**Pull request by dgarciasarai**
Like Preston change: https://github.com/liferay/liferay-portal/commit/805aa95aaf2fb7d023f63564a9ffcb59d3edf5dd

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant - Trying again, GitHub threw an exception on the last attempt

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
As far as I can tell this problem is only happening on this pull request. The build is failing when trying to create/attach labels to this pull request in GitHub. There may be a permissions issue here. I'm  investigating the cause and will report back here with updates when I have any.

**Comment by pyoo47** [comment]
As a workaround, try sending this pull request to a different user.

**Comment by dgarciasarai** [comment]
Thanks @pyoo47 :)

**Comment by michaelhashimoto** [comment]
@dgarciasarai - The reason it's not working is because you probably need to add @liferay-continuous-integration as a collaborator to your repository.

Here's an article describing how to setup pull requests for your repository:
https://grow.liferay.com/share/Pull+Request+Tester+for+Liferay+Developers

> For liferay-portal repositories only you will need to add the user liferay-continuous-integration as a collaborator to your repository. This is so the liferay-continuous-integration user is able to change the status of a commit in the pull request.
> 
> 1. Click Settings on the your fork of the liferay-portal repository
> 2. Click Collaborators
> 3. Type liferay-continuous-integration into the search field
> 4. Click Add collaborator
> 
> This will send a request to have 'liferay-continuous-integration' as a collaborator in your repository.
> 
> The account 'liferay-continuous-integration' needs to manually approve this request.
> 
> Let QA Engineering know if your request needs to be approved: https://loop.liferay.com/web/guest/home/-/loop/teams/_QA+Engineering

**Comment by nhpatt** [comment]
@dgarciasarai I don't know if this is going to work (compileInclude to compileOnly) when you just deploy apio with the whiteboard. Check it. Also, commits to apio-architect should be sent to the subrepo.

**Pull request closed without merging**
