### PR TITLE
COMMERCE-1067

### PR DESCRIPTION
**Pull request by brianchandotcom**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@nhpatt see https://github.com/brianchandotcom/liferay-portal/pull/78801

**Comment by ivicac** [comment]
@nhpatt can you please use this updated PR: https://github.com/nhpatt/liferay-portal/pull/171?

**Comment by nhpatt** [comment]
Ok?

**Comment by nhpatt** [comment]
Sent and resent... :)

**Pull request closed without merging**
