### PR TITLE
LPS-108401 Create AccountRole GET and POST endpoints

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-108401](https://issues.liferay.com/browse/LPS-108401).<br><br>Hey @nhpatt, I'm seeing a couple of test failures on this one. Do I need to change my impl at all?

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
PMD is mine, I think but those test errors are hard to fix automatically, users are not being deleted... entities that don't depend on the site leave a lot of things after a creation. The solution in this case is to override tests to store the created user, as UserAccount is doing.

**Comment by drewbrokke** [comment]
Ok. I'll take another look, but those are different failures than the ones I was getting locally. There was an NPE in `assignAccountRoleHttpResponse`, and the test case was passing `null` for all the parameters twice, but I'm not sure what I should expect from the test case.

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by drewbrokke** [comment]
I just updated to remove the AccountResourceTest failures.

**Comment by nhpatt** [comment]
Just testAssignAccountRole and testUnassignAccountRole failing for me now. I'll check them tomorrow.

**Comment by nhpatt** [comment]
Mmm, I've sent an ignore for the PMD failure but tests look hard to implement automatically:

`AccountRole accountRole = testAssignAccountRole_addAccountRole();

		assertHttpResponseStatusCode(
			204,
			accountRoleResource.assignAccountRoleHttpResponse(
				null, null, null));
@Override
	public void assignAccountRole(
			Long accountId, Long accountRoleId, Long accountUserId)
		throws Exception {

		_accountRoleLocalService.associateUser(
			accountId, accountRoleId, accountUserId);
	}
`
No fields are being field because tests only fill path variables... I could relax that restriction and fill the accountRoleId (from the accountRole) but it's called getRoleId... I don't know automatically that I have to remove account. I could fill accountId, by checking if there is a getter in the entity. But I can't fill accountUserId (no getter or path parameter).

**Comment by drewbrokke** [comment]
@nhpatt got it. Would the solution in this case be to manually override the test case and fill in those values myself?

**Comment by nhpatt** [comment]
Yes :)

**Pull request closed without merging**
