### PR TITLE
LPS-102577 Replace inheritance with adapting service tracker.

### PR DESCRIPTION
**Pull request by Preston-Crary**

### CODE REVIEW

**Comment by Preston-Crary** [comment]
Haven't tested this at all. This removes the compile time dependency.  You may need to do some more work for the adaptor itself or for the service properties.

**Comment by nhpatt** [comment]
Ok, thanks! 

I suggested this solution to BChan but I was worried about having 2 service trackers and performance but I think it's the only option. Thank you so much :)

**Comment by Preston-Crary** [comment]
Service trackers are only slow when used poorly. For example many 100+ opened for similar services or open/close calls when a new service shows up.

**Comment by nhpatt** [comment]
Got it, thanks! :D

**Pull request merged**
