### PR TITLE
LPS-118035 Update Account Headless APIs to support external reference code

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-118035](https://issues.liferay.com/browse/LPS-118035).<br><br>Hi @nhpatt, will you please look over my changes in the last few commits\? Brian asked me to move my custom assertion logic into the templates when an entity has an "externalReferenceCode" and also a "getByExternalReferenceCode" method.<br><br>/cc @pei-jung @alee8888 @ChrisKian @dejuknow @patriciajeanperez

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:test:sf

**Comment by drewbrokke** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
LGTM :)

**Comment by nhpatt** [comment]
Thank you so much! :) Do you want me to send it?

**Comment by drewbrokke** [comment]
Please do! Thank you!

**Comment by drewbrokke** [comment]
@nhpatt I can go ahead and forward.

**Comment by drewbrokke** [comment]
ci:forward

**Comment by nhpatt** [comment]
@drewbrokke Thanks, I was afk :)

**Comment by drewbrokke** [comment]
No worries!

**Pull request closed without merging**
